"""
VyapaarBandhu — PDF Generator Unit Tests
Tests for filing summary PDF generation.

Note: WeasyPrint is not installed in test environment,
so we test the template rendering logic without actual PDF generation.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import Decimal

import pytest
from jinja2 import Template


# Import the template string directly to test rendering without WeasyPrint
import sys
from unittest.mock import MagicMock

# Mock model imports
_mock = MagicMock()
for mod in [
    "app.models", "app.models.client", "app.models.invoice",
    "app.models.ca_account", "app.models.base", "app.models.audit_log",
    "app.models.classification_feedback", "app.models.monthly_summary",
    "app.models.refresh_token", "app.models.reminder_log",
    "weasyprint",
]:
    sys.modules.setdefault(mod, _mock)

from app.services.exports.pdf_generator import PDF_TEMPLATE


@dataclass
class FakeInvoice:
    invoice_number: str = "INV-001"
    invoice_date: str = "2026-03-15"
    seller_gstin: str = "27AAPFU0939F1ZV"
    seller_name: str = "Test Supplier"
    total_amount: Decimal = Decimal("10000.00")
    taxable_amount: Decimal = Decimal("8474.58")
    cgst_amount: Decimal = Decimal("762.71")
    sgst_amount: Decimal = Decimal("762.71")
    igst_amount: Decimal = Decimal("0.00")
    is_itc_eligible_draft: bool = True
    blocked_reason: str = None
    status: str = "ca_approved"


class TestPDFTemplateRendering:
    def _render(self, **kwargs):
        """Render the PDF template with given context."""
        defaults = dict(
            ca_firm_name="Test CA Firm",
            ca_proprietor_name="CA Test Person",
            client_name="Test Business",
            client_gstin="27AAPFU0939F1ZV",
            tax_period="03-2026",
            invoices=[FakeInvoice()],
            confirmed_cgst_itc="762.71",
            confirmed_sgst_itc="762.71",
            confirmed_igst_itc="0.00",
            confirmed_total_itc="1525.42",
            pending_cgst_itc="0.00",
            pending_sgst_itc="0.00",
            pending_igst_itc="0.00",
            pending_total_itc="0.00",
            rejected_cgst_itc="0.00",
            rejected_sgst_itc="0.00",
            rejected_igst_itc="0.00",
            rejected_total_itc="0.00",
            rcm_liability=Decimal("0.00"),
            pending_count=0,
            invoice_count=1,
            flagged_invoices=[],
            generated_at="31 Mar 2026 11:00 UTC",
        )
        defaults.update(kwargs)
        template = Template(PDF_TEMPLATE)
        return template.render(**defaults)

    def test_rcm_liability_as_decimal_no_typeerror(self):
        """CRITICAL: rcm_liability as Decimal must not raise TypeError."""
        # This was a known bug: template comparison {% if rcm_liability > 0 %}
        # would fail if rcm_liability was a string like "0.00"
        html = self._render(rcm_liability=Decimal("0.00"))
        assert "RCM Liability" not in html  # 0.00 should not show RCM section

    def test_rcm_liability_shown_when_positive(self):
        """RCM section should appear when rcm_liability > 0."""
        html = self._render(rcm_liability=Decimal("5000.00"))
        assert "RCM Liability" in html
        assert "5000.00" in html

    def test_footer_text_present(self):
        """Footer must contain 'Generated by VyapaarBandhu | Not a substitute for CA review'."""
        html = self._render()
        assert "Generated by VyapaarBandhu" in html
        assert "Not a substitute for CA review" in html

    def test_ca_firm_name_in_header(self):
        html = self._render(ca_firm_name="My CA Firm LLP")
        assert "My CA Firm LLP" in html

    def test_client_gstin_in_header(self):
        html = self._render(client_gstin="29AAGCB7383J1Z2")
        assert "29AAGCB7383J1Z2" in html

    def test_period_in_header(self):
        html = self._render(tax_period="12-2025")
        assert "12-2025" in html

    def test_pending_notice_shown(self):
        """Pending notice should appear when pending_count > 0."""
        html = self._render(pending_count=3)
        assert "3 invoice(s) pending CA review" in html

    def test_pending_notice_hidden(self):
        """Pending notice should NOT appear when pending_count == 0."""
        html = self._render(pending_count=0)
        assert "pending CA review" not in html

    def test_itc_summary_table_values(self):
        html = self._render(
            confirmed_cgst_itc="900.00",
            confirmed_sgst_itc="900.00",
            confirmed_igst_itc="500.00",
            confirmed_total_itc="2300.00",
        )
        assert "900.00" in html
        assert "500.00" in html
        assert "2300.00" in html

    def test_flagged_invoices_section_shown(self):
        flagged = [FakeInvoice(
            invoice_number="INV-FLAGGED",
            status="flagged_low_confidence",
        )]
        html = self._render(flagged_invoices=flagged)
        assert "Flagged Invoices" in html
        assert "INV-FLAGGED" in html

    def test_flagged_invoices_section_hidden(self):
        html = self._render(flagged_invoices=[])
        assert "Flagged Invoices" not in html

    def test_invoice_details_in_table(self):
        inv = FakeInvoice(invoice_number="INV-123", seller_name="ABC Corp")
        html = self._render(invoices=[inv])
        assert "INV-123" in html
        assert "ABC Corp" in html

    def test_gstin_not_provided_fallback(self):
        html = self._render(client_gstin=None)
        assert "Not provided" in html

    def test_disclaimer_text(self):
        html = self._render()
        assert "supporting document" in html
        assert "GSTR-3B filing on the GSTN portal" in html
